<?php

/**
 * @file
 * Primary module hooks for KonsoliFIN Ads module.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Render\Markup;
use Drupal\konsolifin_ads\Render\AdInjector;

/**
 * Implements hook_page_attachments().
 */
function konsolifin_ads_page_attachments(array &$attachments)
{
  $basePath = \Drupal::service('extension.list.module')->getPath('konsolifin_ads');
  $attachments['#attached']['library'][] = 'konsolifin_ads/ads_setup';

  // CMP script
  $attachments['#attached']['html_head'][] = [
    [
      '#tag' => 'script',
      '#attributes' => [
        'type' => 'text/javascript',
        'async' => TRUE,
      ],
      '#value' => Markup::create(file_get_contents($basePath . '/js/inmobi-cmp.js')),
    ],
    'im_cmp_script'
  ];

  // External Livewrapped ad placement script
  $attachments['#attached']['html_head'][] = [
    [
      '#tag' => 'script',
      '#attributes' => [
        'type' => 'text/javascript',
        'async' => TRUE,
        'src' => 'https://lwadm.com/lw/pbjs?pid=8ebbf627-07b0-41d9-98d1-aad15c4af925',
      ],
    ],
    'im_ad_placement'
  ];

  // Inline ad loading script
  $attachments['#attached']['html_head'][] = [
    [
      '#tag' => 'script',
      '#attributes' => [
        'type' => 'text/javascript',
      ],
      '#value' => Markup::create('var lwhbim = lwhbim || {cmd:[]};'),
    ],
    'im_inline_ad_loader'
  ];
}

function konsolifin_ads_page_bottom(array &$page_bottom)
{
  $page_bottom['anchor_ad'] = [
    '#theme' => 'konsolifin_ad',
    '#base_id' => 'anchor',
    '#unique_suffix' => '',
  ];
}

/**
 * Implements hook_theme().
 */
function konsolifin_ads_theme($existing, $type, $theme, $path)
{
  return [
    'konsolifin_ad' => [
      'variables' => [
        'base_id' => NULL,
        'unique_suffix' => NULL,
      ],
      'template' => 'konsolifin-ad',
    ],
  ];
}

/**
 * Implements hook_entity_view_alter().
 */
function konsolifin_ads_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display)
{
  // Only target nodes in full view mode.
  if ($entity->getEntityTypeId() === 'node' && $build['#view_mode'] === 'full') {
    // Check if the body field is being rendered.
    if (isset($build['body'])) {
      // Add a post-render callback to the body field.
      $build['body']['#post_render'][] = [AdInjector::class, 'postRenderNodeBody'];
    }
  }
}

/**
 * Implements hook_preprocess_views_view().
 */
function konsolifin_ads_preprocess_views_view(&$variables)
{
  $view = $variables['view'];
  if (
    in_array(
      $view->id(),
      [
        'uutiset',
        'artikkelit_blogit_ja_laitearviot',
        'frontpage',
        'peliarvostelut',
        'podcastit',
      ]
    )
  ) {

    if (isset($variables['rows']) && is_array($variables['rows'])) {
      $variables['rows']['#post_render'][] = [AdInjector::class, 'postRenderView'];
    }
  }
}

/**
 * Implements hook_preprocess_page().
 */
function konsolifin_ads_preprocess_page(&$variables)
{
  if (isset($variables['page']) && is_array($variables['page'])) {
    $variables['page']['#post_render'][] = [AdInjector::class, 'postRenderPage'];
  }
}
