<?php

/**
 * Implements hook_preprocess_node().
 */
function konsolifin_misc_preprocess_node(&$variables) {
  $node = $variables['node'];
  $author = $node->getOwner();

  // Load the author's profile picture URL
  if ($author && $author->hasField('user_picture') && !$author->get('user_picture')->isEmpty() && $author->user_picture->entity) {
    $variables['author_headshot'] = [
      '#theme' => 'image_style',
      '#style_name' => 'teaser_thumbnail',
      '#uri' => $author->user_picture->entity->getFileUri(),
      '#alt' => $author->getDisplayName(),
      '#cache' => [
        'tags' => $author->getCacheTags(),
      ],
    ];
  }

  // Load the bio/intro
  if ($author && $author->hasField('field_esittely')) {
    $variables['author_bio'] = $author->field_esittely->view('default');
    // Limit the bio for only the first paragraph
    if (isset($variables['author_bio'][0]['#text'])) {
      $bio_text = $variables['author_bio'][0]['#text'];
      $paragraphs = explode("</p>", $bio_text);
      $variables['author_bio'][0]['#text'] = $paragraphs[0] . '</p>';
    } else {
      // If the field is empty, set it to an empty string to avoid rendering issues
      $variables['author_bio'][0]['#text'] = '';
    }
  }

  // Load social links
  if ($author && $author->hasField('field_some_linkit')) {
    $variables['author_social'] = $author->field_some_linkit->view('default');
  }
}

function konsolifin_misc_preprocess_username(&$variables) {
  $account = $variables['account'];
  
  // Haetaan koko nimi Realname-moduulilta
  if (isset($account->realname)) {
    $variables['name'] = $account->realname;
  } elseif (method_exists($account, 'getDisplayName')) {
    $variables['name'] = $account->getDisplayName();
  }
  
  // Estetään Drupalia lyhentämään nimeä
  $variables['truncated'] = FALSE;
}

// ----------------------------------------
// PATHAUTO HOOKS
// ----------------------------------------

function konsolifin_misc_pathauto_alias_alter(&$alias, array &$context)
{
  // Show the current alias on UI for debugging purposes
  if ($context['module'] == 'node' && isset($context['data']['node'])) {
    $alias_parts = explode('/', $alias);
    $node = $context['data']['node'];

    if ($node->hasField('field_sarja') && !$node->get('field_sarja')->isEmpty()) {
      $term = $node->get('field_sarja')->entity;
      if ($term) {
        $alias = '/' . $alias_parts[1] .
          '/' . \Drupal::service('pathauto.alias_cleaner')->cleanString($term->getName()) .
          '-' . $alias_parts[2];
      }
    }

    if ($node->hasField('field_pelin_nimi') && !$node->get('field_pelin_nimi')->isEmpty()) {
      $alias = $alias . '-' . \Drupal::service('pathauto.alias_cleaner')->cleanString($node->get('field_pelin_nimi')->value);
    }
  }
}
